<!-- Copyright 2026 上海如静知华信息科技有限公司 -->
<script setup>
import AdminShell from '../../components/AdminShell.vue'
import StatusBadge from '../../components/StatusBadge.vue'
import {milestones, tasks} from '../../api/mock'
</script>
<template>
  <AdminShell><template #title>项目工作区</template>
    <div class="page-heading compact"><div><p>PROJECT WORKSPACE</p><h1>华东智能仓储升级</h1><span>PRJ-2026-018 · 澄川智能制造 · 项目经理 陆嘉言</span></div><div><button class="button secondary">项目周报</button><button class="button primary">＋ 添加任务</button></div></div>
    <section class="project-overview"><div class="overview-main"><span>交付验证阶段</span><h2>让上线范围、验收证据和未决事项保持同步</h2><p>当前重点：完成入库策略联调与回归，准备 8 月 5 日 UAT 业务验收。</p><div class="avatars"><i>陆</i><i>江</i><i>许</i><i>顾</i><i>唐</i><b>＋8</b><span>13 名项目成员</span></div></div><div class="overview-score"><small>整体进度</small><b>68%</b><i><em></em></i><span>计划基线 71% · 偏差 -3%</span></div><dl><div><dt>项目预算</dt><dd>¥ 328.0 万</dd></div><div><dt>已确认成本</dt><dd>¥ 186.4 万</dd></div><div><dt>剩余天数</dt><dd>91 天</dd></div><div><dt>健康状态</dt><dd><StatusBadge value="正常"/></dd></div></dl></section>
    <section class="phase-line"><article class="done"><span>01</span><div><b>项目启动</b><small>04/08 — 04/18</small></div><i>✓</i></article><article class="done"><span>02</span><div><b>蓝图设计</b><small>04/21 — 05/30</small></div><i>✓</i></article><article class="done"><span>03</span><div><b>方案实施</b><small>06/02 — 07/24</small></div><i>✓</i></article><article class="active"><span>04</span><div><b>交付验证</b><small>07/27 — 09/05</small></div><i>68%</i></article><article><span>05</span><div><b>上线验收</b><small>09/08 — 10/30</small></div></article></section>
    <div class="workspace-grid"><section class="card"><header><div><h2>里程碑计划</h2><p>项目基线与实际完成情况</p></div><button>管理基线 →</button></header><div class="gantt-head"><span>工作包</span><span>7 月</span><span>8 月</span><span>9 月</span><span>10 月</span></div><div class="gantt-row"><b>方案与配置</b><span class="gantt-bar g1">已完成</span></div><div class="gantt-row"><b>接口与联调</b><span class="gantt-bar g2">进行中 74%</span></div><div class="gantt-row"><b>UAT 与培训</b><span class="gantt-bar g3">待开始</span></div><div class="gantt-row"><b>上线与陪产</b><span class="gantt-bar g4">待开始</span></div><div class="gantt-marker"><i></i><span>今天 07/31</span></div></section>
      <section class="card project-activity"><header><div><h2>项目动态</h2><p>最近 24 小时</p></div><button>全部动态 →</button></header><article><i>江</i><div><b>江叙 更新了任务进度</b><p>入库策略联调与回归：完成度 72% → 89%</p><small>28 分钟前</small></div></article><article><i>陆</i><div><b>陆嘉言 上传了交付物</b><p>《UAT 业务验收方案 V1.3》</p><small>1 小时前</small></div></article><article><i>许</i><div><b>许知遥 新增了待决策事项</b><p>异常入库业务的责任边界确认</p><small>3 小时前</small></div></article></section></div>
    <div class="workspace-grid lower"><section class="card"><header><div><h2>关键任务</h2><p>本周需要完成或验收</p></div><button>查看任务看板 →</button></header><table><thead><tr><th>任务</th><th>负责人</th><th>工时</th><th>到期</th><th>状态</th></tr></thead><tbody><tr v-for="task in tasks.filter(t=>t.project==='PRJ-2026-018')" :key="task.no"><td><b>{{task.title}}</b><small>{{task.no}}</small></td><td><i class="person">{{task.assignee[0]}}</i>{{task.assignee}}</td><td>{{task.logged}} / {{task.estimate}}h</td><td>{{task.due}}</td><td><StatusBadge :value="task.status"/></td></tr></tbody></table></section>
      <section class="card document-list"><header><div><h2>最近交付物</h2><p>项目文档与验收证据</p></div><button>文档空间 →</button></header><article><i>DOC</i><div><b>UAT 业务验收方案 V1.3</b><small>陆嘉言 · 今天 09:42 · 2.8 MB</small></div><span>已评审</span></article><article><i>XLS</i><div><b>接口联调问题清单 0731</b><small>江叙 · 今天 08:18 · 846 KB</small></div><span>处理中</span></article><article><i>PDF</i><div><b>上线范围与验收口径</b><small>许知遥 · 昨天 17:26 · 1.2 MB</small></div><span>已冻结</span></article></section></div>
  </AdminShell>
</template>
