<!-- Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ -->
<script setup>
import AdminShell from '../../components/AdminShell.vue'
import StatusBadge from '../../components/StatusBadge.vue'
import {risks, people} from '../../api/mock'
</script>
<template><AdminShell><template #title>风险与资源</template>
  <div class="page-heading"><div><p>RISK & CAPACITY</p><h1>风险与资源中心</h1><span>集中识别项目风险、资源冲突与工时负荷</span></div><div><button class="button secondary">资源日历</button><button class="button primary">＋ 登记风险</button></div></div>
  <section class="risk-strip"><article><span>开放风险</span><b>17</b><small>较上周 +2</small></article><article><span>高影响风险</span><b class="danger-text">4</b><small>2 项待升级</small></article><article><span>超负荷成员</span><b>6</b><small>集中在研发角色</small></article><article><span>本周可用容量</span><b>312h</b><small>整体利用率 78%</small></article><aside><span>组合风险指数</span><b>6.8</b><i><em></em></i><small>可控，需关注权限与接口风险</small></aside></section>
  <div class="risk-layout"><section class="card risk-register"><header><div><h2>风险登记册</h2><p>按影响程度和更新时间排序</p></div><button>全部风险 →</button></header><table><thead><tr><th>风险事项</th><th>项目</th><th>概率</th><th>影响</th><th>责任人</th><th>应对状态</th><th>下一步行动</th></tr></thead><tbody><tr v-for="risk in risks" :key="risk.no"><td><b>{{risk.title}}</b><small>{{risk.no}}</small></td><td><span class="project-tag">{{risk.project}}</span></td><td><StatusBadge :value="risk.probability"/></td><td><StatusBadge :value="risk.impact"/></td><td><i class="person">{{risk.owner[0]}}</i>{{risk.owner}}</td><td>{{risk.status}}</td><td>{{risk.action}}</td></tr></tbody></table></section><aside class="card risk-matrix"><header><div><h2>风险矩阵</h2><p>概率 × 影响</p></div></header><div class="matrix-label">影响程度</div><div class="matrix"><span class="m1">0</span><span class="m2">1</span><span class="m3">1</span><span class="m2">1</span><span class="m3">2</span><span class="m4">1</span><span class="m1">3</span><span class="m2">4</span><span class="m3">4</span></div><footer><span>低</span><span>中</span><span>高</span><small>发生概率 →</small></footer></aside></div>
  <div class="resource-grid"><section class="card"><header><div><h2>成员负荷</h2><p>未来两周计划分配</p></div><button>打开资源计划 →</button></header><div class="people-table"><div class="table-head"><span>成员 / 角色</span><span>主要项目</span><span>已分配容量</span><span>负荷判断</span></div><article v-for="person in people" :key="person.name"><div><i class="person">{{person.name[0]}}</i><span><b>{{person.name}}</b><small>{{person.role}}</small></span></div><span>{{person.project}}</span><div class="capacity-bar"><i><em :style="{width:person.allocation+'%'}"></em></i><b>{{person.allocation}}%</b></div><StatusBadge :value="person.load"/></article></div></section>
    <section class="card timesheet-panel"><header><div><h2>工时审批概览</h2><p>本周 07/27 — 08/02</p></div><button>进入工时管理 →</button></header><div class="hour-ring"><div><b>86%</b><small>已提交率</small></div><ul><li><span>已通过</span><b>684.5h</b></li><li><span>待审批</span><b>96.0h</b></li><li><span>未提交</span><b>124.0h</b></li></ul></div><footer><span>需在周五 18:00 前完成本周工时确认</span></footer></section></div>
</AdminShell></template>
